zero_optimization:
  stage: 2
  contiguous_gradients: true
  overlap_comm: true
  allgather_partitions: true
  reduce_scatter: true
  allgather_bucket_size: 500000000
  reduce_bucket_size: 500000000

train_micro_batch_size_per_gpu: 1

bf16:
  enabled: true
